name: Playwright E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Start All Services
        run: docker compose up -d --build
      - name: Wait for Backend
        run: npx wait-on --timeout 12000 http://localhost:8080
      - name: Wait for Frontend
        run: npx wait-on --timeout 12000 http://localhost:5173
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend
      - name: Print backend logs if wait-on fails
        if: failure()
        run: docker logs $(docker ps -aqf "name=backend")
